CREATE TABLE User (iduser INTEGER AUTO_INCREMENT NOT NULL, isadmin TINYINT(1) default 0, password VARCHAR(255), username VARCHAR(255), organizationId INTEGER, PRIMARY KEY (iduser))
CREATE TABLE Organization (idorganization INTEGER AUTO_INCREMENT NOT NULL, adminusername VARCHAR(255), extension VARCHAR(255), name VARCHAR(255), PRIMARY KEY (idorganization))
CREATE TABLE Resource (idresource INTEGER AUTO_INCREMENT NOT NULL, name VARCHAR(255), PRIMARY KEY (idresource))
CREATE TABLE UserResource (id INTEGER AUTO_INCREMENT NOT NULL, RIGHT VARCHAR(255), idresource INTEGER, iduser INTEGER, PRIMARY KEY (id))
CREATE TABLE organization_resource (idorganization INTEGER NOT NULL, idresource INTEGER NOT NULL, PRIMARY KEY (idorganization, idresource))
ALTER TABLE User ADD CONSTRAINT FK_User_organizationId FOREIGN KEY (organizationId) REFERENCES Organization (idorganization)
ALTER TABLE UserResource ADD CONSTRAINT FK_UserResource_idresource FOREIGN KEY (idresource) REFERENCES Resource (idresource)
ALTER TABLE UserResource ADD CONSTRAINT FK_UserResource_iduser FOREIGN KEY (iduser) REFERENCES User (iduser)
ALTER TABLE organization_resource ADD CONSTRAINT FK_organization_resource_idorganization FOREIGN KEY (idorganization) REFERENCES Organization (idorganization)
ALTER TABLE organization_resource ADD CONSTRAINT FK_organization_resource_idresource FOREIGN KEY (idresource) REFERENCES Resource (idresource)
